
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gestor-de-tarefas-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/gestor-de-tarefas
      - JWT_SECRET=2b7e1c6e7f8a4d3b9c5f1a2e8d7c6b3a
      - PORT=5000
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gestor-de-tarefas-frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  mongodb:
    image: mongo:6.0
    container_name: gestor-de-tarefas-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local